shape: GShape
nsamples: 1000
ntrain: 4
seed: 1385
width: 100
depth: 3
order: 1
lambda_vel: 0.0
steps: 20000
batch_size: 2
base_lr: 5.0e-4
curriculum_steps: 200
print_every: 100
save_every: 1000
out_root: auto_run/models
